# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

# Adapt as necessary starting from here
branches:
  only:
    - master

environment:
  global:
    WARNINGS_ARE_ERRORS: 0
    R_ARCH: x64
    USE_RTOOLS: true

build_script:
  - travis-tool.sh install_deps
  - travis-tool.sh install_github r-lib/devtools
  - travis-tool.sh install_github r-lib/sessioninfo
  - travis-tool.sh install_github RDatatable/data.table
  - travis-tool.sh install_github tlverse/sl3
  - travis-tool.sh install_github tlverse/tmle3
  - travis-tool.sh install_github tlverse/hal9001
  - travis-tool.sh install_github tlverse/origami

test_script:
  - travis-tool.sh run_tests

on_success:
  - Rscript -e "covr::codecov()"

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

notifications:
 - provider: Email
   to:
     - wcai@berkeley.edu
     - jeremyrcoyle@gmail.com
   subject: 'r-appveyor build {{status}}'
   message: "https://ci.appveyor.com/project/tlverse/ctmle3"
   on_build_success: false
   on_build_failure: true
   on_build_status_changed: true

